---
- name: Install Zookeeper
  hosts: zookeeper_server
  vars:
    install_java: "{{ lookup('env', 'install_java') }}"
    set_hostname_etc_hosts: "{{ lookup('env', 'set_hostname_etc_hosts') }}"
    install_zookeeper: "{{ lookup('env', 'install_zookeeper') }}"
    config_zookeeper: "{{ lookup('env', 'config_zookeeper') }}"
    start_zookeeper: "{{ lookup('env', 'start_zookeeper') }}"
    hostname_suffix: "{{ lookup('env', 'hostname_suffix') }}"
    java_version: "{{ lookup('env', 'java_version') }}"
    zookeeper_type: "{{ lookup('env', 'zookeeper_type') }}"
    zookeeper_user: "{{ lookup('env', 'zookeeper_user') }}"
    zookeeper_port: "{{ lookup('env', 'zookeeper_port') }}"
    zookeeper_home: "{{ lookup('env', 'zookeeper_home') }}"
    zookeeper_etc_path: "{{ lookup('env', 'zookeeper_etc_path') }}"
    zookeeper_data_dir: "{{ lookup('env', 'zookeeper_data_dir') }}"
    zookeeper_log_path: "{{ lookup('env', 'zookeeper_log_path') }}"
    zookeeper_pid_path: "{{ lookup('env', 'zookeeper_pid_path') }}"

  pre_tasks:
    # Zookeeper pre-tasks
    - name: Set zookeeper nodes id
      ansible.builtin.set_fact: id="{{ groups['zookeeper_server'].index(ansible_host) | int + 1 }}"

    - name: Set host's name
      ansible.builtin.set_fact: hosts="zookeeper0{{ id }}.{{ hostname_suffix }}"

    - ansible.builtin.apt: name=curl state=present

    - name: Get zookeeper latest version's number
      ansible.builtin.shell: "curl https://dlcdn.apache.org/zookeeper/stable/ | grep 'bin.tar.gz\"' | cut -d '\"' -f6 | cut -d'-' -f3"
      register: zookeeper_version_raw

    - ansible.builtin.set_fact: zookeeper_version="{{ zookeeper_version_raw.stdout_lines.0 }}"

  roles:
    - java
    - zookeeper
